# Secure Coding Review using Bandit

## Overview

This project demonstrates a basic secure coding review of a Python application. A deliberately vulnerable Python program is analyzed using the Bandit static analysis tool, followed by manual inspection to identify security weaknesses and recommend secure coding practices.

This project was completed as part of a Cyber Security laboratory assignment.

---

## Objectives

- Review source code for security issues
- Perform static code analysis
- Identify insecure coding practices
- Recommend remediation techniques

---

## Technologies Used

- Python 3
- Bandit
- Kali Linux

---

## Project Files

| File | Description |
|------|-------------|
| vulnerable_app.py | Sample application containing security issues |
| findings.txt | Manual security review |
| bandit_report.txt | Static analysis report generated by Bandit |

---

## Installation

Clone the repository

```bash
git clone https://github.com/yourusername/Secure-Coding-Review.git
```

Install Bandit

```bash
pip install bandit
```

---

## Run the Scan

```bash
bandit vulnerable_app.py
```

Generate a report

```bash
bandit -r . -f txt -o bandit_report.txt
```

---

## Vulnerabilities Identified

- Weak password hashing (MD5)
- Command Injection
- Unsafe shell execution
- Missing input validation

---

## Recommendations

- Use bcrypt or Argon2 for password hashing
- Avoid shell=True
- Replace os.system() with safer alternatives
- Validate and sanitize all user input

---

## Learning Outcomes

- Understanding secure coding practices
- Using static analysis tools
- Identifying common vulnerabilities
- Writing security recommendations

---

## Disclaimer

The vulnerable application is intentionally insecure and should only be used for educational purposes.
